// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtIu-kw-Z_kqe477bviJjcGikLnSSNcw',
    appId: '1:695345913798:web:8deac4ccb9483f2c5e5cc7',
    messagingSenderId: '695345913798',
    projectId: 'taskable-6f90c',
    authDomain: 'taskable-6f90c.firebaseapp.com',
    databaseURL: 'https://taskable-6f90c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskable-6f90c.appspot.com',
    measurementId: 'G-N0M4DB0ZN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLbhdykSKKE4qmgMAGYOHA6yy7C7OiUR4',
    appId: '1:695345913798:android:635a400224d96f435e5cc7',
    messagingSenderId: '695345913798',
    projectId: 'taskable-6f90c',
    databaseURL: 'https://taskable-6f90c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskable-6f90c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLvdDqTu2FcfJmHfXyqZtQAwR9EEMwW4',
    appId: '1:695345913798:ios:76c3495fee86d4db5e5cc7',
    messagingSenderId: '695345913798',
    projectId: 'taskable-6f90c',
    databaseURL: 'https://taskable-6f90c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskable-6f90c.appspot.com',
    iosClientId: '695345913798-ctoi2qkd4cd0qo8rka60bb5d3ud5o5ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLvdDqTu2FcfJmHfXyqZtQAwR9EEMwW4',
    appId: '1:695345913798:ios:815a1c7e2b51894e5e5cc7',
    messagingSenderId: '695345913798',
    projectId: 'taskable-6f90c',
    databaseURL: 'https://taskable-6f90c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskable-6f90c.appspot.com',
    iosClientId: '695345913798-j282341orhv2rj61ol0hkk4vvgvfdbm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskable.RunnerTests',
  );
}
